# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scifi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(622, 410)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, -1, 621, 411))
        self.label.setStyleSheet("background-image: url(:/newPrefix/bg3.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("lib/bg3.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, -40, 581, 421))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("lib/gifloader.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(380, 300, 221, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("lib/tuse.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.exitB = QtWidgets.QPushButton(Form)
        self.exitB.setGeometry(QtCore.QRect(20, 300, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.exitB.setFont(font)
        self.exitB.setAutoFillBackground(False)
        self.exitB.setStyleSheet("background-color: rgb(255, 10, 10);")
        self.exitB.setAutoExclusive(False)
        self.exitB.setAutoDefault(False)
        self.exitB.setDefault(False)
        self.exitB.setFlat(False)
        self.exitB.setObjectName("exitB")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(390, 310, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exitB.setText(_translate("Form", "EXIT"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\">16 june 2020</p></body></html>"))
import rec_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
